language: android
android:
  components:
    - build-tools-28.0.3
    - android-28
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-28
    - sys-img-armeabi-v7a-android-24
env:
  global:
    - ADB_INSTALL_TIMEOUT=8
script:
  - "./gradlew build -S"
  - "./gradlew assembleRelease"

